### ISSUE TITLE
can we bundle executable with CUDA??

### ISSUE THREAD

**Issue by hakuturu583** [colcon/colcon-bundle#101]
Hi, I am very interested in colcon bundle and I want to bundle cuda executable.
Can we use CUDA ROS node with colcon bundle??

**Comment by murphm8** [comment]
I would suggest just trying it out. The main question is whether or not you can install all the dependencies. You might need to do some rosdep workarounds to get everything installed.

If you need to add keys to rosdep you can do it locally very similarly to: https://docs.ros.org/independent/api/rosdep/html/contributing_rules.html
