### ISSUE TITLE
Update shebang doesn't work for sh files

### ISSUE THREAD

**Issue by murphm8** [colcon/colcon-bundle#141]
This should be changed to the sh tuple: https://github.com/colcon/colcon-bundle/blob/977de17e48e364c4d7c9bd8858cc3f46e95a4915/colcon_bundle/verb/utilities.py#L98

We also need to make the sh regex specifically for `sh`..The current regex will catch `bash` also.

**Comment by piraka9011** [comment]
Resolved by #154
