### ISSUE TITLE
Ubuntu 20.04 with Noetic support

### ISSUE THREAD

**Issue by obi-t4** [colcon/colcon-bundle#168]
Current implementation does not seems to support ubuntu20.04 and Noetic.
Is there any plans to support it?
https://github.com/colcon/colcon-bundle/blob/ac14862e61f17a8f65b0b8dcffe165dfb7b82d2a/colcon_bundle/verb/utilities.py#L39-L44

**Comment by thomas-moulard** [comment]
Thank you for the contribution, I think this should solve this ticket, feel free to re-open the issue if any additional work is needed.
