### ISSUE TITLE
colcon bundle is intermittently failing to fetch apt packages

### ISSUE THREAD

**Issue by ojasjoshi** [colcon/colcon-bundle#178]
## Description
 * colcon bundle is intermittently failing to fetch apt packages in Travis CI build tests for [Cloudwatch Sample Apps](https://github.com/aws-robotics/aws-robomaker-sample-application-cloudwatch) for both ROS1/ROS2 branches.
 * the frequency of the build failure resulting from this issue is 1 to 3 times a week
 * the [first build failure](https://travis-ci.org/github/aws-robotics/aws-robomaker-sample-application-cloudwatch/jobs/707059604) occurred about ~1.5 months ago and has been occurring intermittently since then
 * build gets fixed by itself

### Error Messages 
```bash
ERROR:colcon.colcon_bundle.verb:Could not fetch from repositories: W:Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://packages.ros.org/ros2/ubuntu bionic InRelease' doesn't support architecture 'i386', E:Failed to fetch http://mirror.enzu.com/ubuntu/dists/bionic-security/multiverse/binary-i386/Packages.xz  Hash Sum mismatch
 ```
or
```bash
ERROR:colcon.colcon_bundle.verb:Could not fetch from repositories: W:Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://packages.ros.org/ros2/ubuntu bionic InRelease' doesn't support architecture 'i386', E:Failed to fetch http://mirror.enzu.com/ubuntu/dists/bionic-security/multiverse/source/Sources.gz  Hash Sum mismatch
```
or
```bash
 ERROR:colcon:colcon bundle: Failed to fetch http://ubuntu.mirrors.pair.com/archive/pool/universe/libz/libzip/libzip-dev_1.1.2-1.1_amd64.deb Hash Sum mismatch
```

**Comment by emersonknapp** [comment]
Closing for now, please reopen if issue reappears
