### ISSUE TITLE
Dynamic libraries not found when deploying on ARM64

### ISSUE THREAD

**Issue by massi-ang** [colcon/colcon-bundle#192]
Running roscore after sourcing the dependency bundle generates errors due to incorrect LD_LIBRARY_PATH.

The path in https://github.com/colcon/colcon-bundle/blob/master/colcon_bundle/verb/assets/v1_setup.sh only contains x86_64 and armhf paths.

**Comment by emersonknapp** [comment]
Fixed via https://github.com/colcon/colcon-bundle/pull/193
